dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t moddable-esp32 .
      - docker images
      - docker tag moddable-esp32 stargatestudio/moddable-esp32
      - docker push stargatestudio/moddable-esp32
